/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OpenFMS;

import OpenFMS.field.Arena;

public class App {
    static Arena field;

    public static void main(String[] args) {
        field = new Arena();

        // Start FMS
        field.run();
    }
}
